### ISSUE TITLE
Interaction of application is limited to CommandBox and ResultDisplay

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-W12-4/main#125]
**Describe the bug**
After executing multiple commands, added drinks should be populated in the bottom side of the UI, else, there is no additional functionality from AB3

**Expected behavior**
The interaction of the application should not be limited to the two areas and the list of drinks currently in stock should be displayed in the application

**Screenshots**
![image](https://user-images.githubusercontent.com/37281349/47907257-d2b80900-dec5-11e8-896a-41b89aa625f2.png)

<hr>

**Reported by:** @cjinting-nus
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#406]</sub>

**Comment by Lunastryke** [comment]
Problem with jar file that they tested. Works fine on our side. Will test more with other people
