### ISSUE TITLE
Drink increaseQuantity etc tests and Batch increase tests

### ISSUE THREAD

**Issue by bluein-green** [CS2113-AY1819S1-W12-4/main#139]
> buy command does not have a date field yet. Ideally the buy command should have an optional date field.

@Lunastryke 
The buy command's date is the same as the transaction date, and this is generated automatically using the system's date when the buy command object is created. We can pass the transaction date downwards to the `Batch` class if needed. Would that be ok?

_Originally posted by @bluein-green in https://github.com/CS2113-AY1819S1-W12-4/main/pull/138#issuecomment-435653084_

**Comment by Lunastryke** [comment]
Hmm but that means the date of the batch will always be the date the command is typed in right
@bluein-green

**Comment by Lunastryke** [comment]
I was thinking for demo purposes, we allow the date to differ. If not when we demo, there will always only be 1 batch displayed which doesnt really demo the capabilities of the app

**Comment by bluein-green** [comment]
Hmm. We have to pre-load some data into the app for the demo, so we could pre-load batches with different dates (so have > 1 batches). Would that be ok? Seems a bit inappropriate to do change date only for demo purposes. And by the time of the demo, we would already have submitted the project.

**Comment by Lunastryke** [comment]
Oh if we preload then its fine. I just worried that if only show 1 batch doesnt really display the functionality
