### ISSUE TITLE
Travis does not show exceptions for failed tests

### ISSUE THREAD

**Issue by bluein-green** [CS2113-AY1819S1-W12-4/main#7]
Failed test outputs are saved in the Travis VM, so we don't have access to the actual build reports.

I've made a PR that has build.gradle edited as per this [link](https://stackoverflow.com/questions/28614865/how-to-read-test-result-reports-on-travis-ci). Could someone more familiar with Travis try to test it?

**Comment by LIU-TIANHANG** [comment]
i see my error under ./gradlew assemble..
not sure if this helps..
